FROM ubuntu:22.04

RUN apt update && apt-get upgrade -y
RUN apt install -y lsb-release wget software-properties-common gpg-agent sudo --no-install-recommends

RUN wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
RUN add-apt-repository -y "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main"

RUN apt update && apt-get upgrade -y

# Install llvm
RUN apt install -y clang-19 lldb-19 lld-19 clangd-19

# Install other build deps
RUN apt install -y git build-essential automake autoconf pkg-config libtool-bin

ENV CC="clang-19"

WORKDIR /build
COPY libmagic_unix.sh .
RUN chmod +x libmagic_unix.sh
