# Based on https://github.com/trailofbits/llvm-docker
FROM alpine:latest

# Install build deps
RUN apk add git build-base automake autoconf pkgconfig libtool

# Install llvm
RUN apk add clang19

ENV CC="clang-19"
ENV CHOST="x86_64-unknown-linux-musl"

WORKDIR /build
COPY libmagic_unix.sh .
RUN chmod +x libmagic_unix.sh
